# Generated by Django 4.0.1 on 2022-01-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('key', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cart_id', models.PositiveIntegerField()),
                ('product_id', models.PositiveIntegerField()),
                ('product_count', models.PositiveIntegerField()),
            ],
        ),
    ]
